# Generated by Django 6.0.1 on 2026-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_alumnos_options_alter_alumnos_matricula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Fotos', verbose_name='Fotografia'),
        ),
    ]
